#Start with a base image containing Java runtime
FROM java:1.8

#maake port 8080 available to the world outside this container
EXPOSE 8080

#rUN THE JAR FILE
ENTRYPOINT["java","-jar","Test05.jar"]